src/Entity/Groupe.php
<?php

/*
 * Copyright (c) 2023. | Cyndel Herolt | IUT de Troyes  - All Rights Reserved
 * @author cyndelherolt
 * @project UniFolio
 */
namespace App\Entity;

use App\Repository\GroupeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GroupeRepository::class)]
class Groupe
{
    #[ORM\Id]
//    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $libelle = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $code_apogee = null;

    #[ORM\Column(nullable: true)]
    private ?int $ordre = null;

    #[ORM\ManyToOne(inversedBy: 'groupes')]
    private ?TypeGroupe $type_groupe = null;

    #[ORM\ManyToMany(targetEntity: Etudiant::class, mappedBy: 'groupe')]
    private Collection $etudiants;

    #[ORM\ManyToOne(inversedBy: 'groupes')]
    private ?ApcParcours $apcParcours = null;

    public function __construct()
    {
        $this->etudiants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(?string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getCodeApogee(): ?string
    {
        return $this->code_apogee;
    }

    public function setCodeApogee(?string $code_apogee): self
    {
        $this->code_apogee = $code_apogee;

        return $this;
    }

    public function getOrdre(): ?int
    {
        return $this->ordre;
    }

    public function setOrdre(?int $ordre): self
    {
        $this->ordre = $ordre;

        return $this;
    }

    public function getTypeGroupe(): ?TypeGroupe
    {
        return $this->type_groupe;
    }

    public function setTypeGroupe(?TypeGroupe $type_groupe): self
    {
        $this->type_groupe = $type_groupe;

        return $this;
    }

    /**
     * @return Collection<int, Etudiant>
     */
    public function getEtudiants(): Collection
    {
        return $this->etudiants;
    }

    public function addEtudiant(Etudiant $etudiant): self
    {
        if (!$this->etudiants->contains($etudiant)) {
            $this->etudiants->add($etudiant);
            $etudiant->addGroupe($this);
        }

        return $this;
    }

    public function removeEtudiant(Etudiant $etudiant): self
    {
        if ($this->etudiants->removeElement($etudiant)) {
            $etudiant->removeGroupe($this);
        }

        return $this;
    }

    public function getApcParcours(): ?ApcParcours
    {
        return $this->apcParcours;
    }

    public function setApcParcours(?ApcParcours $apcParcours): self
    {
        $this->apcParcours = $apcParcours;

        return $this;
    }
}

src/Controller/ProfilController.php
<?php

/*
 * Copyright (c) 2023. | Cyndel Herolt | IUT de Troyes  - All Rights Reserved
 * @author cyndelherolt
 * @project UniFolio
 */

namespace App\Controller;

use App\Entity\Enseignant;
use App\Entity\Etudiant;
use App\Entity\Users;
use App\Form\EnseignantType;
use App\Form\EtudiantPartialType;
use App\Repository\EnseignantRepository;
use App\Repository\EtudiantRepository;
use App\Repository\UsersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Contracts\Service\Attribute\Required;

#[Route('/profil')]
class ProfilController extends BaseController
{
    public function __construct(
        #[Required] public Security $security,
    )
    {
    }

    #[Route('/', name: 'app_profil')]
    public function profil(UsersRepository $usersRepository): Response
    {
        $data_user = $this->dataUserSession;
//        dd($data_user);
        $user = $usersRepository->findOneBy(['username' => $this->getUser()->getUserIdentifier()]);
        $userId = $this->getUser()->getUserIdentifier();

        if ($this->isGranted('ROLE_ETUDIANT')) {
            $etudiant = $user->getEtudiant();

            // Si un objet Etudiant est trouvé, vous pouvez accéder à ses propriétés
            if ($etudiant instanceof Etudiant) {
                $nom = $etudiant->getNom();
                $prenom = $etudiant->getPrenom();
                $email_perso = $etudiant->getMailPerso();
                $email_univ = $etudiant->getMailUniv();
                $tel = $etudiant->getTelephone();
                $bio = $etudiant->getBio();
                $optAlt = $etudiant->isOptAlternance();
                $optStage = $etudiant->isOptStage();
            }
        } elseif ($this->isGranted('ROLE_ENSEIGNANT')) {
            $enseignant = $user->getEnseignant();

            // Si un objet Enseignant est trouvé, vous pouvez accéder à ses propriétés
            if ($enseignant instanceof Enseignant) {
                $nom = $enseignant->getNom();
                $prenom = $enseignant->getPrenom();
                $email_perso = $enseignant->getMailPerso();
                $email_univ = $enseignant->getMailUniv();
                $tel = $enseignant->getTelephone();
                $groupes = $enseignant->getGroupes();
                $bio = null;
            }
        } else {
            return $this->render('security/accessDenied.html.twig');
        }

        return $this->render('profil/index.html.twig', [
            'user' => $userId,
            'prenom' => $prenom,
            'nom' => $nom,
            'email_perso' => $email_perso,
            'email_univ' => $email_univ,
            'tel' => $tel,
            'bio' => $bio,
            'optAlternance' => $optAlt ?? null,
            'optStage' => $optStage ?? null,
            'groupes' => $groupes ?? null,
            'data_user' => $data_user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_profil_edit', methods: ['GET', 'POST'])]
    public function edit(
        Request              $request,
        ?Etudiant            $etudiant,
        ?Enseignant          $enseignant,
        EtudiantRepository   $etudiantRepository,
        EnseignantRepository $enseignantRepository,
        ?int                 $id,
    ): Response
    {
        $user = $this->security->getUser();

        if ($this->isGranted('ROLE_ETUDIANT')) {
            if ($id == $user->getEtudiant()->getId()) {
                $form = $this->createForm(EtudiantPartialType::class, $etudiant);
            } else {
                return $this->render('security/accessDenied.html.twig');
            }
        } elseif ($this->isGranted('ROLE_ENSEIGNANT')) {
            if ($id == $user->getEnseignant()->getId()) {
                $form = $this->createForm(EnseignantType::class, $enseignant);
            } else {
                return $this->render('security/accessDenied.html.twig');
            }
        } else {
            return $this->render('security/accessDenied.html.twig');
        }

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($this->isGranted('ROLE_ETUDIANT')) {
                if ($form->get('optAlternance')->getData() == true && $form->get('optStage')->getData() == true) {
                    // Si l'étudiant est à la recherche d'une alternance et d'un stage, on ne peut pas valider le formulaire
                    $this->addFlash('danger', 'Vous ne pouvez pas être à la recherche d\'une alternance et d\'un stage en même temps');
                    // redirection vers la page d'édition du profil
                    return $this->redirectToRoute('app_profil_edit', ['id' => $etudiant->getId()], Response::HTTP_SEE_OTHER);
                }
                $etudiantRepository->save($etudiant, true);
            } elseif ($this->isGranted('ROLE_ENSEIGNANT')) {
                $enseignantRepository->save($enseignant, true);
            }

            return $this->redirectToRoute('app_profil', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('profil/edit.html.twig', [
            'enseignant' => $enseignant,
            'etudiant' => $etudiant,
            'form' => $form->createView(),
        ]);
    }
}

templates/profil/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/profil/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}UniFolio - Profil edition{% endblock %}

{% block body %}
    <div class="content-container cv_form">
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ path('app_dashboard') }}">Tableau de bord</a></li>
                <li class="breadcrumb-item"><a href="{{ path('app_profil') }}">Profil</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edition profil</li>
            </ol>
        </nav>
        <section>
            <div class="card">
                <article>
                    <h1>Edition du profil</h1>

                    {{ include('profil/_form.html.twig', {'button_label': 'Enregistrer'}) }}
                </article>
            </div>
        </section>
    </div>
    {#    <a href="{{ path('app_profil_edit_index') }}">back to list</a> #}

    {#    {{ include('profil_edit/_delete_form.html.twig') }} #}
{% endblock %}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}UniFolio - Profil{% endblock %}

{% block body %}

    <div class="content-container">
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ path('app_dashboard') }}">Tableau de bord</a></li>
                <li class="breadcrumb-item active" aria-current="page">Profil</li>
            </ol>
        </nav>
        <section class="profil">
            <div class="container my-4">
                <div class="row g-4">
                    <div>
                        <h1>Profil</h1>
                        <em>Vos informations personnelles et universitaires</em>
                    </div>
                    <div class="col-lg-4 mb-3">
                        <div class="card" style="padding: 1.5rem">
                            {#                            <img src="{{ asset('logo.png') }}" class="card-img-top" alt="{{ prenom }} {{ nom }}" style="max-width: 200px; margin: 0 auto; border-radius: 50%; border: solid 1px #c7c7c7"> #}
                            <div class="card-body">
                                <h5 class="card-title text-center">{{ prenom }} {{ nom }}</h5>
                                <p class="text-center">
                                    {{ is_granted('ROLE_ETUDIANT') ? 'Étudiant·e' : 'Enseignant·e' }}</p>

                                {% if is_granted('ROLE_ETUDIANT') %}
                                    {% if optAlternance == true %}
                                        <hr>
                                        <div class="text-center alert alert-info" style="margin: 25px 0">
                                            <i class="fa-regular fa-eye"></i>
                                            <span>Recherche une alternance</span>
                                        </div>
                                    {% elseif optStage == true %}
                                        <hr>
                                        <div class="text-center alert alert-info" style="margin: 25px 0">
                                            <i class="fa-regular fa-eye"></i>
                                            <span>Recherche un stage</span>
                                        </div>
                                    {% endif %}
                                {% endif %}

                                <a href="{{ path('app_profil_edit', {'id': is_granted('ROLE_ETUDIANT') ? app.user.etudiant.id : app.user.enseignant.id}) }}"
                                   class="btn btn-primary w-100">Editer le profil</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="card mb-3" style="padding: 1rem">
                            <div class="card-body">
                                <h5 class="card-title"> Informations Générales
                                </h5>
                                <p><i class="fa fa-envelope"></i> Mail universitaire : {{ email_univ }}</p>
                                <p><i class="fa fa-envelope-open"></i> Mail personnel : {{ email_perso }}</p>
                                <p><i class="fa fa-phone"></i> Téléphone : {{ tel }}</p>
                                {% if is_granted('ROLE_ETUDIANT') %}
                                    <p><i class="fa fa-info-circle"></i> Bio : {{ bio }}</p>
                                {% endif %}
                            </div>
                        </div>
                        <div class="card" style="padding: 1rem">
                            <div class="card-body">
                                <h5 class="card-title">Informations Universitaires
                                </h5>
                                {% if is_granted('ROLE_ETUDIANT') %}
                                <p><i class="fa fa-book"></i> Diplôme
                                    : {{ data_user.etudiant.semestre.annee.diplome.libelle }}
                                </p>
                                <p><i class="fa fa-graduation-cap"></i> Semestre
                                    : {{ data_user.etudiant.semestre.libelle }}</p>
                                <p><i class="fa fa-users"></i> Groupes TP :
                                    {% for groupe in data_user.etudiant.groupe %}
                                        {% if groupe.typeGroupe.libelle == "TP" %}
                                        TP {{ groupe.libelle }}
                                        {% endif %}
                                    {% endfor %}
                                </p>
                                {% else %}
                                <p><i class="fa fa-building"></i> Département par défaut :
                                    {% for dept in data_user.departementDefaut %}
                                        {{ dept.libelle }}
                                    {% endfor %}
                                </p>
                                <p><i class="fa fa-buildings"></i> Départements :
                                    {% for dept in data_user.allDepartementsEnseignant %}
                                        {{ dept.libelle }} |
                                    {% endfor %}
                                    {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}